apiVersion: apps/v1
kind: Deployment
metadata:
  name: netting
spec:
  selector:
    matchLabels:
      run: netting
  replicas: 2
  template:
    metadata:
      labels:
        run: netting
    spec:
      containers:
      - name: netting
        image: netting:v3
        ports:
        - containerPort: 50051
          protocol: TCP
